In [5]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']

In [6]:
np.arange(0, 20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [7]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [8]:
a = np.array([[1,2],[3,4]])

In [9]:
np.transpose(a
             )

array([[1, 3],
       [2, 4]])

In [10]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]

In [11]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]

In [12]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,32,93,39]))
demo_matrix[2,3]

39

In [13]:
import pandas as pd
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

In [ ]:
pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

In [ ]:
import numpy as np
demo_array = np.arange(10,17)
demo_array [:]= 101
demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [ ]:
import pandas as pd
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [ ]:
import pandas
import seaborn as sns
data=sns.load_dataset('tips')

In [ ]:
pd.pivot_table(data=data, values='total_bill', index='sex', columns='day', aggfunc='mean')

day          Thur        Fri        Sat        Sun
sex
Male    18.714667  19.857000  20.802542  21.887241
Female  16.715312  14.145556  19.680357  19.872222

In [ ]:
pandas.pivot_table(data=data, values='total_bill', index='day', columns='sex', aggfunc='mean')

sex        Male     Female
day
Thur  18.714667  16.715312
Fri   19.857000  14.145556
Sat   20.802542  19.680357
Sun   21.887241  19.872222

In [ ]:
pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')

C:\Users\rers9\AppData\Local\Temp\ipykernel_1092\2585661749.py:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')

Empty DataFrame
Columns: []
Index: [Male, Female]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from scipy.stats import binom
binom.pmf(k = 7,n = 10, p = 0.6)

0.21499084799999987

In [ ]:
from scipy.stats import binom
1 - binom.cdf(k = 5,n = 15, p = 0.75)

0.9992050509899855

In [ ]:
from scipy.stats import binom
1 - binom.pmf(k = 6,n = 15, p = 0.75)

0.9966019345447421

In [ ]:
from scipy.stats import norm

norm.cdf(590,502,115) - norm.cdf(400,502,115)

0.5903777927789047

In [ ]:
from scipy.stats import t

norm.interval(0.95, loc = 180, scale = 36)

(109.44129655655806, 250.55870344344194)

In [ ]:
import numpy as np

np.random.randint(0,2)

0

In [ ]:
import numpy as np

In [ ]:
a = [[2,1],[3,4]]

In [ ]:
len(a)

2

In [ ]:
a = 2
input(a)

'a'

In [ ]:
input("adgas","fdsafdsaf")

TypeError: raw_input() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
"a"+"b"

'ab'

In [ ]:
for i in range(2):
    print(i)

0
1

In [ ]:
sum(["a","b"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
"sadfsdaf".find("a")

1

In [ ]:
barco  = [[1,2,3],[4,5,6],[7,8,9]]
barco[:][2]

[7, 8, 9]

In [ ]:
a = "asd"

In [ ]:
a.find("sd")

1

In [ ]:
a.find("c")

-1

In [ ]:
import math

In [ ]:
math.perm(4,2)

12

In [ ]:
math.ceil(2.5)

3

In [ ]:
def climbStairs( n):
        prev = 1
        prev2 = 0
        for i in range(1, n+1):
            curi = prev + prev2
            prev2 = prev
            prev = curi
        return prev

In [ ]:
climbStairs(7)

21

In [ ]:
def climbStairs(n: int) -> int:
        prev = 1
        prev_prev = 0
        for _ in range(n):
            prev_prev, prev = prev, prev + prev_prev
        return prev

In [ ]:
climbStairs(7)

NameError: name 'climbStairs' is not defined

In [ ]:
import os
os.path.isfile("curso.py")

True

In [8]:
with open('archivo.txt','w') as txt:
    txt.write("-- Personajes --\n")
    txt.write("-- Usuarios --\n")

In [20]:
with open('archivo.txt','r+') as txt:
    asd = txt.readlines()

asd.index("-- Usuarios --\n")
asd.insert(1,"usuario1"+"\n")

In [21]:
with open('archivo2.txt','w') as txt:
    txt.writelines(asd)

In [22]:
# ventana 109
#283
#294
a = [1,2]

In [23]:
a

[1, 2]

In [25]:
a.append((3,4))

In [26]:
a

[1, 2, (3, 4)]

In [27]:
(3,4) in a

True

In [28]:
import random

mylist = ["apple", "banana", "cherry"]
random.shuffle(list(random.shuffle(mylist)))

print(mylist)

TypeError: 'NoneType' object is not iterable

In [29]:
a = []

In [30]:
a.pop()

IndexError: pop from empty list

In [1]:
print("$",end="")

$

In [4]:
"""=SI(
    Y(N2>=4;N2<=15);
SI(
    Y($K$1>0;$K$1<=375.24);
        ($K$1-$I$1)/($H$1-$I$1)*($B$3+N2*$B$4+N2^2*$B$5+N2^3*$B$6+N2^4*$B$7+N2^5*$B$8+N2^6*$B$9+N2^7*$B$10+N2^8*$B$11+N2^9*$B$12+N2^10*$B$13+N2^11*$B$14)/100+
        (1-($K$1-$I$1)/($H$1-$I$1))*($C$3+N2*$C$4+N2^2*$C$5+N2^3*$C$6+N2^4*$C$7+N2^5*$C$8+N2^6*$C$9+N2^7*$C$10+N2^8*$C$11+N2^9*$C$12+N2^10*$C$13+N2^11*$C$14)/100;
    SI(
        Y($K$1>0;$K$1>375.24);
            ($K$1-$J$1)/($I$1-$J$1)*($C$3+N2*$C$4+N2^2*$C$5+N2^3*$C$6+N2^4*$C$7+N2^5*$C$8+N2^6*$C$9+N2^7*$C$10+N2^8*$C$11+N2^9*$C$12+N2^10*$C$13+N2^11*$C$14)/100+
            (1-($K$1-$J$1)/($I$1-$J$1))*($D$3+N2*$D$4+N2^2*$D$5+N2^3*$D$6+N2^4*$D$7+N2^5*$D$8+N2^6*$D$9+N2^7*$D$10+N2^8*$D$11+N2^9*$D$12+N2^10*$D$13+N2^11*$D$14)/100;0));0)"""

'=SI(Y(N2>=4;N2<=15);\nSI(Y($K$1>0;$K$1<=375.24);($K$1-$I$1)/($H$1-$I$1)*($B$3+N2*$B$4+N2^2*$B$5+N2^3*$B$6+N2^4*$B$7+N2^5*$B$8+N2^6*$B$9+N2^7*$B$10+N2^8*$B$11+N2^9*$B$12+N2^10*$B$13+N2^11*$B$14)/100+(1-($K$1-$I$1)/($H$1-$I$1))*($C$3+N2*$C$4+N2^2*$C$5+N2^3*$C$6+N2^4*$C$7+N2^5*$C$8+N2^6*$C$9+N2^7*$C$10+N2^8*$C$11+N2^9*$C$12+N2^10*$C$13+N2^11*$C$14)/100;SI(Y($K$1>0;$K$1>375.24);($K$1-$J$1)/($I$1-$J$1)*($C$3+N2*$C$4+N2^2*$C$5+N2^3*$C$6+N2^4*$C$7+N2^5*$C$8+N2^6*$C$9+N2^7*$C$10+N2^8*$C$11+N2^9*$C$12+N2^10*$C$13+N2^11*$C$14)/100+(1-($K$1-$J$1)/($I$1-$J$1))*($D$3+N2*$D$4+N2^2*$D$5+N2^3*$D$6+N2^4*$D$7+N2^5*$D$8+N2^6*$D$9+N2^7*$D$10+N2^8*$D$11+N2^9*$D$12+N2^10*$D$13+N2^11*$D$14)/100;0));0)'

In [94]:
Ef = "X"
Pt = "Y"
altura = "R"
caudal1 = "I"
caudal2 = "J"
desde = 3
hojaPE = "PE!"
hojaPP = "PP!"
alturas = "$1"
polinomios = 2 #al 7
columnas_pol = "B,C,D,E,F,G,H,I,J,K,L".split(",")
max_Q = 28
min_Q = 5
actual = "X3"
def SI(a,b,c):
    return "SI("+str(a)+";"+str(b)+";"+str(c)+")"
def pol(letrapol,actual, n = 7,hoja = ""): #grado 7
    ret = ""
    for x in range(n+1):
        if x ==0:
            ret += hoja +"$"+str(letrapol) + "$" + str(x+2)
        else:
            ret += "+"+actual+"^" + str(x) +"*"+hoja+"$"+str(letrapol) + "$" + str(x+2)
    return ret
def caudal_valido(actual):
    return "Y("+str(actual)+">="+str(min_Q)+";"+str(actual)+"<="+str(max_Q)+")"
def ponderacion_cruzada(altura,h1,h2,hoja = ""):
    return "($"+str(altura)+str(desde)+"-"+hoja+"$"+str(h2)+"$1)/("+hoja+"$"+str(h1)+"$1-"+hoja+"$"+str(h2)+"$1)"
def par_pol(altura,h1,h2,actual,hoja=""):
    return ponderacion_cruzada(altura,h1,h2,hoja=hoja) +"*("+pol(h1,actual,hoja = hoja)+ ")+(1-" + ponderacion_cruzada(altura,h1,h2,hoja = hoja) +")*("+pol(h2,actual,hoja = hoja)+")"
def Y(altura,h1,h2,hoja=""):
    return "Y("+"$"+str(altura)+str(desde)+">="+hoja+"$"+str(h1)+"$1"+";"+"$"+str(altura)+str(desde)+"<"+hoja+"$"+str(h2)+"$1"+")"

In [95]:
par_pol(altura,"D","E",caudal1+"3",hoja = hojaPE)

'($R3-PE!$E$1)/(PE!$D$1-PE!$E$1)*(PE!$D$2+I3^1*PE!$D$3+I3^2*PE!$D$4+I3^3*PE!$D$5+I3^4*PE!$D$6+I3^5*PE!$D$7+I3^6*PE!$D$8+I3^7*PE!$D$9)+(1-($R3-PE!$E$1)/(PE!$D$1-PE!$E$1))*(PE!$E$2+I3^1*PE!$E$3+I3^2*PE!$E$4+I3^3*PE!$E$5+I3^4*PE!$E$6+I3^5*PE!$E$7+I3^6*PE!$E$8+I3^7*PE!$E$9)'

In [96]:
Y(altura,"D","E",hoja = hojaPE)

'Y($R3>=PE!$D$1;$R3<PE!$E$1)'

In [97]:
result = ""
for a in range(len(columnas_pol)-3):
    h1 = columnas_pol[-3-a:-1-a][0]
    h2 = columnas_pol[-3-a:-1-a][1]
    #print(h1,h2)
    if a == 0:
        result += SI(Y(altura,h1,h2,hoja=hojaPE),par_pol(altura,h1,h2,caudal1+"3",hoja = hojaPE),0)
    else:
        result = SI(Y(altura,h1,h2,hoja=hojaPE),par_pol(altura,h1,h2,caudal1+"3",hoja = hojaPE),result)

result = SI(caudal_valido(caudal1+"3"),result,0)
result = "=" + result
print(result)

=SI(Y(I3>=5;I3<=28);SI(Y($R3>=PE!$C$1;$R3<PE!$D$1);($R3-PE!$D$1)/(PE!$C$1-PE!$D$1)*(PE!$C$2+I3^1*PE!$C$3+I3^2*PE!$C$4+I3^3*PE!$C$5+I3^4*PE!$C$6+I3^5*PE!$C$7+I3^6*PE!$C$8+I3^7*PE!$C$9)+(1-($R3-PE!$D$1)/(PE!$C$1-PE!$D$1))*(PE!$D$2+I3^1*PE!$D$3+I3^2*PE!$D$4+I3^3*PE!$D$5+I3^4*PE!$D$6+I3^5*PE!$D$7+I3^6*PE!$D$8+I3^7*PE!$D$9);SI(Y($R3>=PE!$D$1;$R3<PE!$E$1);($R3-PE!$E$1)/(PE!$D$1-PE!$E$1)*(PE!$D$2+I3^1*PE!$D$3+I3^2*PE!$D$4+I3^3*PE!$D$5+I3^4*PE!$D$6+I3^5*PE!$D$7+I3^6*PE!$D$8+I3^7*PE!$D$9)+(1-($R3-PE!$E$1)/(PE!$D$1-PE!$E$1))*(PE!$E$2+I3^1*PE!$E$3+I3^2*PE!$E$4+I3^3*PE!$E$5+I3^4*PE!$E$6+I3^5*PE!$E$7+I3^6*PE!$E$8+I3^7*PE!$E$9);SI(Y($R3>=PE!$E$1;$R3<PE!$F$1);($R3-PE!$F$1)/(PE!$E$1-PE!$F$1)*(PE!$E$2+I3^1*PE!$E$3+I3^2*PE!$E$4+I3^3*PE!$E$5+I3^4*PE!$E$6+I3^5*PE!$E$7+I3^6*PE!$E$8+I3^7*PE!$E$9)+(1-($R3-PE!$F$1)/(PE!$E$1-PE!$F$1))*(PE!$F$2+I3^1*PE!$F$3+I3^2*PE!$F$4+I3^3*PE!$F$5+I3^4*PE!$F$6+I3^5*PE!$F$7+I3^6*PE!$F$8+I3^7*PE!$F$9);SI(Y($R3>=PE!$F$1;$R3<PE!$G$1);($R3-PE!$G$1)/(PE!$F$1-PE!$G$1)*(PE!$F$2+I3^1*PE!$F$3+I3^2*PE!$F$4+I3^3*PE!$F$5+I3^4*PE!$F$6+I3^5*PE!$F$7+I3^6*PE!$F$8+I3^7*PE!$F$9)+(1-($R3-PE!$G$1)/(PE!$F$1-PE!$G$1))*(PE!$G$2+I3^1*PE!$G$3+I3^2*PE!$G$4+I3^3*PE!$G$5+I3^4*PE!$G$6+I3^5*PE!$G$7+I3^6*PE!$G$8+I3^7*PE!$G$9);SI(Y($R3>=PE!$G$1;$R3<PE!$H$1);($R3-PE!$H$1)/(PE!$G$1-PE!$H$1)*(PE!$G$2+I3^1*PE!$G$3+I3^2*PE!$G$4+I3^3*PE!$G$5+I3^4*PE!$G$6+I3^5*PE!$G$7+I3^6*PE!$G$8+I3^7*PE!$G$9)+(1-($R3-PE!$H$1)/(PE!$G$1-PE!$H$1))*(PE!$H$2+I3^1*PE!$H$3+I3^2*PE!$H$4+I3^3*PE!$H$5+I3^4*PE!$H$6+I3^5*PE!$H$7+I3^6*PE!$H$8+I3^7*PE!$H$9);SI(Y($R3>=PE!$H$1;$R3<PE!$I$1);($R3-PE!$I$1)/(PE!$H$1-PE!$I$1)*(PE!$H$2+I3^1*PE!$H$3+I3^2*PE!$H$4+I3^3*PE!$H$5+I3^4*PE!$H$6+I3^5*PE!$H$7+I3^6*PE!$H$8+I3^7*PE!$H$9)+(1-($R3-PE!$I$1)/(PE!$H$1-PE!$I$1))*(PE!$I$2+I3^1*PE!$I$3+I3^2*PE!$I$4+I3^3*PE!$I$5+I3^4*PE!$I$6+I3^5*PE!$I$7+I3^6*PE!$I$8+I3^7*PE!$I$9);SI(Y($R3>=PE!$I$1;$R3<PE!$J$1);($R3-PE!$J$1)/(PE!$I$1-PE!$J$1)*(PE!$I$2+I3^1*PE!$I$3+I3^2*PE!$I$4+I3^3*PE!$I$5+I3^4*PE!$I$6+I3^5*PE!$I$7+I3^6*PE!$I$8+I3^7*PE!$I$9)+(1-($R3-PE!$J$1)/(PE!$I$1-PE!$J$1))*(PE!$J$2+I3^1*PE!$J$3+I3^2*PE!$J$4+I3^3*PE!$J$5+I3^4*PE!$J$6+I3^5*PE!$J$7+I3^6*PE!$J$8+I3^7*PE!$J$9);SI(Y($R3>=PE!$J$1;$R3<PE!$K$1);($R3-PE!$K$1)/(PE!$J$1-PE!$K$1)*(PE!$J$2+I3^1*PE!$J$3+I3^2*PE!$J$4+I3^3*PE!$J$5+I3^4*PE!$J$6+I3^5*PE!$J$7+I3^6*PE!$J$8+I3^7*PE!$J$9)+(1-($R3-PE!$K$1)/(PE!$J$1-PE!$K$1))*(PE!$K$2+I3^1*PE!$K$3+I3^2*PE!$K$4+I3^3*PE!$K$5+I3^4*PE!$K$6+I3^5*PE!$K$7+I3^6*PE!$K$8+I3^7*PE!$K$9);0))))))));0)

In [101]:
result = ""
def pol(letrapol,actual, n = 2,hoja = ""): #grado 2
    ret = ""
    for x in range(n+1):
        if x ==0:
            ret += hoja +"$"+str(letrapol) + "$" + str(x+2)
        else:
            ret += "+"+actual+"^" + str(x) +"*"+hoja+"$"+str(letrapol) + "$" + str(x+2)
    return ret
for a in range(len(columnas_pol)-3):
    h1 = columnas_pol[-3-a:-1-a][0]
    h2 = columnas_pol[-3-a:-1-a][1]
    #print(h1,h2)
    if a == 0:
        result += SI(Y(altura,h1,h2,hoja=hojaPP),par_pol(altura,h1,h2,caudal1+"3",hoja = hojaPP),0)
    else:
        result = SI(Y(altura,h1,h2,hoja=hojaPP),par_pol(altura,h1,h2,caudal1+"3",hoja = hojaPP),result)

result = SI(caudal_valido(caudal1+"3"),result,0)
result = "=" + result
print(result)

=SI(Y(I3>=5;I3<=28);SI(Y($R3>=PP!$C$1;$R3<PP!$D$1);($R3-PP!$D$1)/(PP!$C$1-PP!$D$1)*(PP!$C$2+I3^1*PP!$C$3+I3^2*PP!$C$4)+(1-($R3-PP!$D$1)/(PP!$C$1-PP!$D$1))*(PP!$D$2+I3^1*PP!$D$3+I3^2*PP!$D$4);SI(Y($R3>=PP!$D$1;$R3<PP!$E$1);($R3-PP!$E$1)/(PP!$D$1-PP!$E$1)*(PP!$D$2+I3^1*PP!$D$3+I3^2*PP!$D$4)+(1-($R3-PP!$E$1)/(PP!$D$1-PP!$E$1))*(PP!$E$2+I3^1*PP!$E$3+I3^2*PP!$E$4);SI(Y($R3>=PP!$E$1;$R3<PP!$F$1);($R3-PP!$F$1)/(PP!$E$1-PP!$F$1)*(PP!$E$2+I3^1*PP!$E$3+I3^2*PP!$E$4)+(1-($R3-PP!$F$1)/(PP!$E$1-PP!$F$1))*(PP!$F$2+I3^1*PP!$F$3+I3^2*PP!$F$4);SI(Y($R3>=PP!$F$1;$R3<PP!$G$1);($R3-PP!$G$1)/(PP!$F$1-PP!$G$1)*(PP!$F$2+I3^1*PP!$F$3+I3^2*PP!$F$4)+(1-($R3-PP!$G$1)/(PP!$F$1-PP!$G$1))*(PP!$G$2+I3^1*PP!$G$3+I3^2*PP!$G$4);SI(Y($R3>=PP!$G$1;$R3<PP!$H$1);($R3-PP!$H$1)/(PP!$G$1-PP!$H$1)*(PP!$G$2+I3^1*PP!$G$3+I3^2*PP!$G$4)+(1-($R3-PP!$H$1)/(PP!$G$1-PP!$H$1))*(PP!$H$2+I3^1*PP!$H$3+I3^2*PP!$H$4);SI(Y($R3>=PP!$H$1;$R3<PP!$I$1);($R3-PP!$I$1)/(PP!$H$1-PP!$I$1)*(PP!$H$2+I3^1*PP!$H$3+I3^2*PP!$H$4)+(1-($R3-PP!$I$1)/(PP!$H$1-PP!$I$1))*(PP!$I$2+I3^1*PP!$I$3+I3^2*PP!$I$4);SI(Y($R3>=PP!$I$1;$R3<PP!$J$1);($R3-PP!$J$1)/(PP!$I$1-PP!$J$1)*(PP!$I$2+I3^1*PP!$I$3+I3^2*PP!$I$4)+(1-($R3-PP!$J$1)/(PP!$I$1-PP!$J$1))*(PP!$J$2+I3^1*PP!$J$3+I3^2*PP!$J$4);SI(Y($R3>=PP!$J$1;$R3<PP!$K$1);($R3-PP!$K$1)/(PP!$J$1-PP!$K$1)*(PP!$J$2+I3^1*PP!$J$3+I3^2*PP!$J$4)+(1-($R3-PP!$K$1)/(PP!$J$1-PP!$K$1))*(PP!$K$2+I3^1*PP!$K$3+I3^2*PP!$K$4);0))))))));0)

In [104]:
def pol(letrapol,actual, n = 7,hoja = ""): #grado 7
    ret = ""
    for x in range(n+1):
        if x ==0:
            ret += hoja +"$"+str(letrapol) + "$" + str(x+2)
        else:
            ret += "+"+actual+"^" + str(x) +"*"+hoja+"$"+str(letrapol) + "$" + str(x+2)
    return ret

result = ""
for a in range(len(columnas_pol)-3):
    h1 = columnas_pol[-3-a:-1-a][0]
    h2 = columnas_pol[-3-a:-1-a][1]
    #print(h1,h2)
    if a == 0:
        result += SI(Y(altura,h1,h2,hoja=hojaPE),par_pol(altura,h1,h2,caudal2+"3",hoja = hojaPE),0)
    else:
        result = SI(Y(altura,h1,h2,hoja=hojaPE),par_pol(altura,h1,h2,caudal2+"3",hoja = hojaPE),result)

result = SI(caudal_valido(caudal2+"3"),result,0)
result = "=" + result
print(result)

=SI(Y(J3>=5;J3<=28);SI(Y($R3>=PE!$C$1;$R3<PE!$D$1);($R3-PE!$D$1)/(PE!$C$1-PE!$D$1)*(PE!$C$2+J3^1*PE!$C$3+J3^2*PE!$C$4+J3^3*PE!$C$5+J3^4*PE!$C$6+J3^5*PE!$C$7+J3^6*PE!$C$8+J3^7*PE!$C$9)+(1-($R3-PE!$D$1)/(PE!$C$1-PE!$D$1))*(PE!$D$2+J3^1*PE!$D$3+J3^2*PE!$D$4+J3^3*PE!$D$5+J3^4*PE!$D$6+J3^5*PE!$D$7+J3^6*PE!$D$8+J3^7*PE!$D$9);SI(Y($R3>=PE!$D$1;$R3<PE!$E$1);($R3-PE!$E$1)/(PE!$D$1-PE!$E$1)*(PE!$D$2+J3^1*PE!$D$3+J3^2*PE!$D$4+J3^3*PE!$D$5+J3^4*PE!$D$6+J3^5*PE!$D$7+J3^6*PE!$D$8+J3^7*PE!$D$9)+(1-($R3-PE!$E$1)/(PE!$D$1-PE!$E$1))*(PE!$E$2+J3^1*PE!$E$3+J3^2*PE!$E$4+J3^3*PE!$E$5+J3^4*PE!$E$6+J3^5*PE!$E$7+J3^6*PE!$E$8+J3^7*PE!$E$9);SI(Y($R3>=PE!$E$1;$R3<PE!$F$1);($R3-PE!$F$1)/(PE!$E$1-PE!$F$1)*(PE!$E$2+J3^1*PE!$E$3+J3^2*PE!$E$4+J3^3*PE!$E$5+J3^4*PE!$E$6+J3^5*PE!$E$7+J3^6*PE!$E$8+J3^7*PE!$E$9)+(1-($R3-PE!$F$1)/(PE!$E$1-PE!$F$1))*(PE!$F$2+J3^1*PE!$F$3+J3^2*PE!$F$4+J3^3*PE!$F$5+J3^4*PE!$F$6+J3^5*PE!$F$7+J3^6*PE!$F$8+J3^7*PE!$F$9);SI(Y($R3>=PE!$F$1;$R3<PE!$G$1);($R3-PE!$G$1)/(PE!$F$1-PE!$G$1)*(PE!$F$2+J3^1*PE!$F$3+J3^2*PE!$F$4+J3^3*PE!$F$5+J3^4*PE!$F$6+J3^5*PE!$F$7+J3^6*PE!$F$8+J3^7*PE!$F$9)+(1-($R3-PE!$G$1)/(PE!$F$1-PE!$G$1))*(PE!$G$2+J3^1*PE!$G$3+J3^2*PE!$G$4+J3^3*PE!$G$5+J3^4*PE!$G$6+J3^5*PE!$G$7+J3^6*PE!$G$8+J3^7*PE!$G$9);SI(Y($R3>=PE!$G$1;$R3<PE!$H$1);($R3-PE!$H$1)/(PE!$G$1-PE!$H$1)*(PE!$G$2+J3^1*PE!$G$3+J3^2*PE!$G$4+J3^3*PE!$G$5+J3^4*PE!$G$6+J3^5*PE!$G$7+J3^6*PE!$G$8+J3^7*PE!$G$9)+(1-($R3-PE!$H$1)/(PE!$G$1-PE!$H$1))*(PE!$H$2+J3^1*PE!$H$3+J3^2*PE!$H$4+J3^3*PE!$H$5+J3^4*PE!$H$6+J3^5*PE!$H$7+J3^6*PE!$H$8+J3^7*PE!$H$9);SI(Y($R3>=PE!$H$1;$R3<PE!$I$1);($R3-PE!$I$1)/(PE!$H$1-PE!$I$1)*(PE!$H$2+J3^1*PE!$H$3+J3^2*PE!$H$4+J3^3*PE!$H$5+J3^4*PE!$H$6+J3^5*PE!$H$7+J3^6*PE!$H$8+J3^7*PE!$H$9)+(1-($R3-PE!$I$1)/(PE!$H$1-PE!$I$1))*(PE!$I$2+J3^1*PE!$I$3+J3^2*PE!$I$4+J3^3*PE!$I$5+J3^4*PE!$I$6+J3^5*PE!$I$7+J3^6*PE!$I$8+J3^7*PE!$I$9);SI(Y($R3>=PE!$I$1;$R3<PE!$J$1);($R3-PE!$J$1)/(PE!$I$1-PE!$J$1)*(PE!$I$2+J3^1*PE!$I$3+J3^2*PE!$I$4+J3^3*PE!$I$5+J3^4*PE!$I$6+J3^5*PE!$I$7+J3^6*PE!$I$8+J3^7*PE!$I$9)+(1-($R3-PE!$J$1)/(PE!$I$1-PE!$J$1))*(PE!$J$2+J3^1*PE!$J$3+J3^2*PE!$J$4+J3^3*PE!$J$5+J3^4*PE!$J$6+J3^5*PE!$J$7+J3^6*PE!$J$8+J3^7*PE!$J$9);SI(Y($R3>=PE!$J$1;$R3<PE!$K$1);($R3-PE!$K$1)/(PE!$J$1-PE!$K$1)*(PE!$J$2+J3^1*PE!$J$3+J3^2*PE!$J$4+J3^3*PE!$J$5+J3^4*PE!$J$6+J3^5*PE!$J$7+J3^6*PE!$J$8+J3^7*PE!$J$9)+(1-($R3-PE!$K$1)/(PE!$J$1-PE!$K$1))*(PE!$K$2+J3^1*PE!$K$3+J3^2*PE!$K$4+J3^3*PE!$K$5+J3^4*PE!$K$6+J3^5*PE!$K$7+J3^6*PE!$K$8+J3^7*PE!$K$9);0))))))));0)

In [105]:
result = ""
def pol(letrapol,actual, n = 2,hoja = ""): #grado 2
    ret = ""
    for x in range(n+1):
        if x ==0:
            ret += hoja +"$"+str(letrapol) + "$" + str(x+2)
        else:
            ret += "+"+actual+"^" + str(x) +"*"+hoja+"$"+str(letrapol) + "$" + str(x+2)
    return ret
for a in range(len(columnas_pol)-3):
    h1 = columnas_pol[-3-a:-1-a][0]
    h2 = columnas_pol[-3-a:-1-a][1]
    #print(h1,h2)
    if a == 0:
        result += SI(Y(altura,h1,h2,hoja=hojaPP),par_pol(altura,h1,h2,caudal2+"3",hoja = hojaPP),0)
    else:
        result = SI(Y(altura,h1,h2,hoja=hojaPP),par_pol(altura,h1,h2,caudal2+"3",hoja = hojaPP),result)

result = SI(caudal_valido(caudal2+"3"),result,0)
result = "=" + result
print(result)

=SI(Y(J3>=5;J3<=28);SI(Y($R3>=PP!$C$1;$R3<PP!$D$1);($R3-PP!$D$1)/(PP!$C$1-PP!$D$1)*(PP!$C$2+J3^1*PP!$C$3+J3^2*PP!$C$4)+(1-($R3-PP!$D$1)/(PP!$C$1-PP!$D$1))*(PP!$D$2+J3^1*PP!$D$3+J3^2*PP!$D$4);SI(Y($R3>=PP!$D$1;$R3<PP!$E$1);($R3-PP!$E$1)/(PP!$D$1-PP!$E$1)*(PP!$D$2+J3^1*PP!$D$3+J3^2*PP!$D$4)+(1-($R3-PP!$E$1)/(PP!$D$1-PP!$E$1))*(PP!$E$2+J3^1*PP!$E$3+J3^2*PP!$E$4);SI(Y($R3>=PP!$E$1;$R3<PP!$F$1);($R3-PP!$F$1)/(PP!$E$1-PP!$F$1)*(PP!$E$2+J3^1*PP!$E$3+J3^2*PP!$E$4)+(1-($R3-PP!$F$1)/(PP!$E$1-PP!$F$1))*(PP!$F$2+J3^1*PP!$F$3+J3^2*PP!$F$4);SI(Y($R3>=PP!$F$1;$R3<PP!$G$1);($R3-PP!$G$1)/(PP!$F$1-PP!$G$1)*(PP!$F$2+J3^1*PP!$F$3+J3^2*PP!$F$4)+(1-($R3-PP!$G$1)/(PP!$F$1-PP!$G$1))*(PP!$G$2+J3^1*PP!$G$3+J3^2*PP!$G$4);SI(Y($R3>=PP!$G$1;$R3<PP!$H$1);($R3-PP!$H$1)/(PP!$G$1-PP!$H$1)*(PP!$G$2+J3^1*PP!$G$3+J3^2*PP!$G$4)+(1-($R3-PP!$H$1)/(PP!$G$1-PP!$H$1))*(PP!$H$2+J3^1*PP!$H$3+J3^2*PP!$H$4);SI(Y($R3>=PP!$H$1;$R3<PP!$I$1);($R3-PP!$I$1)/(PP!$H$1-PP!$I$1)*(PP!$H$2+J3^1*PP!$H$3+J3^2*PP!$H$4)+(1-($R3-PP!$I$1)/(PP!$H$1-PP!$I$1))*(PP!$I$2+J3^1*PP!$I$3+J3^2*PP!$I$4);SI(Y($R3>=PP!$I$1;$R3<PP!$J$1);($R3-PP!$J$1)/(PP!$I$1-PP!$J$1)*(PP!$I$2+J3^1*PP!$I$3+J3^2*PP!$I$4)+(1-($R3-PP!$J$1)/(PP!$I$1-PP!$J$1))*(PP!$J$2+J3^1*PP!$J$3+J3^2*PP!$J$4);SI(Y($R3>=PP!$J$1;$R3<PP!$K$1);($R3-PP!$K$1)/(PP!$J$1-PP!$K$1)*(PP!$J$2+J3^1*PP!$J$3+J3^2*PP!$J$4)+(1-($R3-PP!$K$1)/(PP!$J$1-PP!$K$1))*(PP!$K$2+J3^1*PP!$K$3+J3^2*PP!$K$4);0))))))));0)

In [2]:
print("asda".split("t"))

['asda']

In [8]:
"s" in "asd"

True

In [15]:
a = "Planta/Veneno"

In [18]:
if tipo in tipo_pokemon:
    break

True

In [19]:
a

'Planta/Veneno'

In [20]:
a.lower()

'planta/veneno'